ALTER TABLE "bet_recommendations"
  ADD COLUMN "fairProb" DOUBLE PRECISION,
  ADD COLUMN "marketProb" DOUBLE PRECISION,
  ADD COLUMN "edge" DOUBLE PRECISION,
  ADD COLUMN "ev" DOUBLE PRECISION,
  ADD COLUMN "isFallback" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN "fallbackReason" TEXT;
